/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aaron_jnitester3_myNDK */

#ifndef _Included_com_aaron_jnitester3_myNDK
#define _Included_com_aaron_jnitester3_myNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aaron_jnitester3_myNDK
 * Method:    getMycstring
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aaron_jnitester3_myNDK_getMycstring
  (JNIEnv *, jobject);

/*
 * Class:     com_aaron_jnitester3_myNDK
 * Method:    getJniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_aaron_jnitester3_myNDK_getJniAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
